CREATE TABLE db_tp.roles (
	id_rol INT NOT NULL AUTO_INCREMENT,
    nombre_rol VARCHAR(50) NOT NULL,
    PRIMARY KEY (id_rol) 
);

INSERT INTO roles (nombre_rol)
VALUES
('ORGANIZADOR'),
('REPRESENTANTE'),
('TEAM LEADER'),
('LIDER TECNICO'),
('SUPERVISOR');

SELECT * FROM roles